export const RARITY = {
  COMMON: 1,
  UNCOMMON: 2,
  RARE: 3,
  LEGENDARY: 4,
};

export const RARITY_NAMES = {
  1: "Обычный",
  2: "Необычный",
  3: "Редкий",
  4: "Легендарный",
};

export const RARITY_COLORS = {
  1: "#aaa",
  2: "#4488ff",
  3: "#aa44ff",
  4: "#ff4444",
};

export const RARITY_EFFECT_MULT = {
  1: 1,
  2: 1.5,
  3: 2,
  4: 3,
};

export const RARITY_COST_MULT = {
  1: 1,
  2: 1.8,
  3: 3,
  4: 5,
};

export const CATEGORIES = [
  { id: "basic", name: "Базовое", icon: "D" },
  { id: "economy", name: "Экономика", icon: "●" },
  { id: "maintenance", name: "Обслуживание", icon: "💧" },
  { id: "heat", name: "Нагрев", icon: "🔥" },
  { id: "выживание", name: "Выживание", icon: "❤️" },
  { id: "поиск_бреши", name: "Поиск бреши", icon: "🎯" },
  { id: "ракеты", name: "Ракеты", icon: "🚀" },
  { id: "контур", name: "Контур", icon: "⚡" },
  { id: "навигация", name: "Навигация", icon: "🔭" },
  { id: "алхимия", name: "Алхимия", icon: "⚗️" },
];

export const INITIAL_CATEGORIES = ["basic", "economy"];
export const TAG_SYNERGIES = {};

export const ALL_EQUIPMENT = [
  {
    id: "thermo_drill",
    type: "equipment",
    name: "Термобур",
    icon: "🔥",
    desc: "Урон 20 (+15% dmg). +1 урона за каждые 10 heat.",
    category: "heat",
    tags: ["heat"],
    minRarity: 2,
    baseCost: 40,
  },
  {
    id: "basic_drill",
    type: "equipment",
    name: "Просто дрель",
    icon: "D",
    desc: "Урон 10 (10% dmg).",
    category: "basic",
    tags: ["basic"],
    minRarity: 1,
    baseCost: 30,
  },
  {
    id: "fragile_drill",
    type: "equipment",
    name: "Хрупкий бур",
    icon: "🪟",
    desc: "Урон 10 (10% dmg). +10% скорость пока есть броня.",
    category: "выживание",
    tags: ["выживание"],
    minRarity: 1,
    baseCost: 35,
  },
  {
    id: "lucky_pickaxe",
    type: "equipment",
    name: "Кирка счастливчика",
    icon: "⛏️",
    desc: "Урон 10 (10% dmg, 10% luck). При ударе по золотой жиле увеличит ее ценность на 1.",
    category: "economy",
    tags: ["economy"],
    minRarity: 1,
    baseCost: 30,
  },
];

export const ALL_ITEMS = [
  {
    id: "heavy_drill",
    type: "item",
    name: "Утяжелитель",
    icon: "⚒️",
    desc: "+3 drillPower. Скорость −10%.",
    category: "basic",
    tags: ["basic"],
    minRarity: 1,
    baseCost: 35,
    effect: [
      { stat: "drillPower",   effectByRarity: [null, 3, 5, 8, 12] },
      { stat: "strikeSpeed",  effectByRarity: [null, -10, -12, -15, -18] },
    ],
  },
  {
    id: "planning",
    type: "item",
    name: "Планирование",
    icon: "🗒️",
    desc: "+1% скорость замыкания контура.",
    category: "контур",
    tags: ["контур"],
    minRarity: 1,
    baseCost: 30,
    effect: {
      stat: "speedOfAutoClose",
      effectByRarity: [null, 3, 5, 8, 10],
    },
  },
  {
    id: "steel_hull",
    type: "item",
    name: "Стальной корпус",
    icon: "🛡️",
    desc: "+1 макс. ЖЗН.",
    category: "выживание",
    tags: ["выживание"],
    minRarity: 1,
    baseCost: 50,
    effect: { stat: "maxHp", value: 1 },
  },
  {
    id: "afterburner",
    type: "item",
    name: "Форсажная камера",
    icon: "💨",
    desc: "+15% скорость бура. −1 макс. HP (не ниже 1).",
    category: "maintenance",
    tags: ["maintenance"],
    minRarity: 1,
    baseCost: 60,
    effect: [
      { stat: "strikeSpeed", effectByRarity: [null, 15, 22, 30, 40] },
      { stat: "maxHp",       effectByRarity: [null, -1, -1, -1, -1] },
    ],
  },
  {
    id: "artifact_compass",
    type: "item",
    name: "Компас артефакта",
    icon: "🔮",
    desc: "Радары маяков показывают фиолетовый указатель на ближайший артефакт.",
    category: "навигация",
    tags: ["навигация"],
    minRarity: 3,
    maxRarity: 3,
    baseCost: 54,
    unique: true,
    effect: { stat: "artifactRadarMode", value: 1 },
  },
  {
    id: "gold_fever",
    type: "item",
    name: "Золотая лихорадка",
    icon: "🤑",
    desc: "+10% к золоту с жил.",
    category: "economy",
    tags: ["economy"],
    minRarity: 1,
    baseCost: 35,
    effect: { stat: "miningGoldBonusMultiplier", effectByRarity: [null, 0.1, 0.15, 0.2, 0.3] },
  },
  {
    id: "gold_probe",
    type: "item",
    name: "Золотой щуп",
    icon: "✨",
    desc: "Радары маяков показывают жёлтый указатель на ближайшее золотое скопление (5+ блоков).",
    category: "навигация",
    tags: ["навигация"],
    minRarity: 2,
    maxRarity: 2,
    baseCost: 45,
    unique: true,
    effect: { stat: "goldRadarMode", value: 1 },
  },
  {
    id: "navigator",
    type: "item",
    name: "Навигатор",
    icon: "📡",
    desc: "Радары маяков показывают белый указатель на ближайший неактивированный маяк на той же глубине.",
    category: "навигация",
    tags: ["навигация"],
    minRarity: 1,
    baseCost: 50,
    unique: true,
    maxRarity: 1,
    effect: { stat: "navigatorMode", value: 1 },
  },
  {
    id: "machine_oil",
    type: "item",
    name: "Машинное масло",
    icon: "💧",
    desc: "+5% скорость бура.",
    category: "maintenance",
    tags: ["maintenance"],
    minRarity: 1,
    baseCost: 30,
    effect: {
      stat: "strikeSpeed",
      effectByRarity: [null, 5, 8, 10, 13],
    },
  },
  {
    id: "geo_sight",
    type: "item",
    name: "Геологический прицел",
    icon: "🔭",
    desc: "+3% шанс бреши в породе.",
    category: "поиск_бреши",
    tags: ["поиск_бреши"],
    minRarity: 1,
    baseCost: 35,
    effect: {
      stat: "weakSpotChance",
      effectByRarity: [null, 0.03, 0.05, 0.08, 0.10],
    },
  },
  // ─── Level-up bonus items ──────────────────────────────────────────────────
  // Each of these grants a bonus every time the player gains a level.
  {
    id: "learning_algorithm",
    type: "item",
    name: "Учебный алгоритм",
    icon: "🧠",
    desc: "При каждом уровне: +0.35 к силе удара бура.",
    category: "basic",
    tags: ["basic"],
    minRarity: 1,
    baseCost: 40,
    effect: {
      stat: "drillPowerPerLevel",
      effectByRarity: [null, 0.35, 0.5, 0.7, 1.0],
    },
  },
  {
    id: "fuel_impulse",
    type: "item",
    name: "Топливный импульс",
    icon: "⚗️",
    desc: "При каждом уровне: +50 топлива.",
    category: "maintenance",
    tags: ["maintenance"],
    minRarity: 1,
    baseCost: 35,
    effect: {
      stat: "fuelPerLevel",
      effectByRarity: [null, 50, 75, 100, 150],
    },
  },
  {
    id: "rapid_adaptation",
    type: "item",
    name: "Ускоренная адаптация",
    icon: "🔩",
    desc: "При каждом уровне: +2% скорости бура.",
    category: "maintenance",
    tags: ["maintenance"],
    minRarity: 1,
    baseCost: 35,
    effect: {
      stat: "strikeSpeedPerLevel",
      effectByRarity: [null, 2, 3, 4, 6],
    },
  },
  {
    id: "experience_regen",
    type: "item",
    name: "Регенерация через опыт",
    icon: "💉",
    desc: "При каждом уровне: лечит +1 HP.",
    category: "выживание",
    tags: ["выживание"],
    minRarity: 1,
    baseCost: 50,
    effect: {
      stat: "healPerLevel",
      effectByRarity: [null, 1, 1, 2, 3],
    },
  },
  {
    id: "golden_wisdom",
    type: "item",
    name: "Золотая мудрость",
    icon: "💡",
    desc: "При каждом уровне: +2% к золоту с жил.",
    category: "economy",
    tags: ["economy"],
    minRarity: 1,
    baseCost: 35,
    effect: {
      stat: "goldBonusPerLevel",
      effectByRarity: [null, 0.02, 0.03, 0.04, 0.06],
    },
  },
  {
    id: "explosive_condenser",
    type: "item",
    name: "Взрывной конденсор",
    icon: "💥",
    desc: "При перегреве взрыв сильнее и шире. −10% концентрация.",
    category: "heat",
    tags: ["heat"],
    minRarity: 1,
    baseCost: 40,
    effect: [
      { stat: "heatExplosionDamageBonus", effectByRarity: [null, 0.25, 0.50, 0.75, 1.00] },
      { stat: "heatExplosionRadiusBonus", effectByRarity: [null, 0.5,  1.0,  1.5,  2.0 ] },
      { stat: "concentration",            effectByRarity: [null, -0.10, -0.15, -0.20, -0.30] },
    ],
  },
  {
    id: "cooling_circuit",
    type: "item",
    name: "Охлаждающий контур",
    icon: "❄️",
    desc: "−15% скорость нагрева. −10% концентрация.",
    category: "heat",
    tags: ["heat"],
    minRarity: 1,
    baseCost: 35,
    effect: [
      { stat: "heatRate",      effectByRarity: [null, -0.15, -0.20, -0.30, -0.40] },
      { stat: "concentration", effectByRarity: [null, -0.10, -0.15, -0.20, -0.30] },
    ],
  },
  {
    id: "first_strike",
    type: "item",
    name: "Инициатор",
    icon: "⚔️",
    desc: "+40% урон бура 6 сек после активации маяка.",
    category: "maintenance",
    tags: ["maintenance"],
    minRarity: 2,
    baseCost: 45,
    effect: { stat: "firstStrikeLevel", effectByRarity: [null, null, 1, 1, 2] },
  },
  {
    id: "boosted_feed",
    type: "item",
    name: "Форсированная подача",
    icon: "🚀",
    desc: "+20% скорость бура. +15% расход топлива.",
    category: "maintenance",
    tags: ["maintenance"],
    minRarity: 1,
    baseCost: 35,
    effect: [
      { stat: "strikeSpeed",  effectByRarity: [null, 20, 28, 38, 50] },
      { stat: "fuelDrainRate",effectByRarity: [null, 0.15, 0.20, 0.25, 0.30] },
    ],
  },
  {
    id: "scanner_lens",
    type: "item",
    name: "Линза сканера",
    icon: "🔭",
    desc: "+1 радиус обзора.",
    category: "basic",
    tags: ["basic"],
    minRarity: 1,
    baseCost: 35,
    effect: { stat: "visionRadius", effectByRarity: [null, 1, 2, 3, 4] },
  },
  {
    id: "insider",
    type: "item",
    name: "Инсайдер",
    icon: "🎲",
    desc: "+2 удача. −3% опыт.",
    category: "economy",
    tags: ["economy"],
    minRarity: 1,
    baseCost: 35,
    effect: [
      { stat: "luck",             effectByRarity: [null, 2,     3,     5,     8    ] },
      { stat: "xpBonusMultiplier",effectByRarity: [null, -0.03, -0.05, -0.07, -0.10] },
    ],
  },
  {
    id: "fuel_converter",
    type: "item",
    name: "Переработчик топлива",
    icon: "♻️",
    desc: "Пополнение сверх макс. топлива → форсаж 3 сек.",
    category: "выживание",
    tags: ["выживание"],
    minRarity: 2,
    baseCost: 50,
    effect: { stat: "fuelConverterLevel", effectByRarity: [null, null, 1, 2, 3] },
  },
  {
    id: "insurance",
    type: "item",
    name: "Страховка",
    icon: "📋",
    desc: "При уроне сохраняет 30% небезопасного золота.",
    category: "выживание",
    tags: ["выживание"],
    minRarity: 2,
    baseCost: 50,
    effect: { stat: "insuranceLevel", effectByRarity: [null, null, 1, 2, 3] },
  },
  {
    id: "adrenaline",
    type: "item",
    name: "Адреналин",
    icon: "💉",
    desc: "+30% скорость бура при HP ≤ 1.",
    category: "выживание",
    tags: ["выживание"],
    minRarity: 2,
    baseCost: 45,
    effect: { stat: "adrenalineLevel", effectByRarity: [null, null, 1, 1, 2] },
  },
  {
    id: "expanded_tank",
    type: "item",
    name: "Расширенный бак",
    icon: "⛽",
    desc: "+80 макс. топливо. +10% расход.",
    category: "выживание",
    tags: ["выживание"],
    minRarity: 1,
    baseCost: 40,
    effect: [
      { stat: "maxFuel",      effectByRarity: [null,  80,  120,  180,  250] },
      { stat: "fuelDrainRate",effectByRarity: [null, 0.10, 0.15, 0.20, 0.30] },
    ],
  },
  {
    id: "heat_accumulator",
    type: "item",
    name: "Термоаккумулятор",
    icon: "🌡️",
    desc: "+15 макс. нагрев.",
    category: "heat",
    tags: ["heat"],
    minRarity: 1,
    baseCost: 35,
    effect: { stat: "maxHeat", effectByRarity: [null, 15, 25, 40, 60] },
  },
  {
    id: "perfectionist",
    type: "item",
    name: "Перфекционист",
    icon: "🏅",
    desc: "+10% золото с жил. −10% шанс находки.",
    category: "economy",
    tags: ["economy"],
    minRarity: 2,
    baseCost: 45,
    effect: [
      { stat: "miningGoldBonusMultiplier", effectByRarity: [null, null, 0.10, 0.18, 0.28] },
      { stat: "bonusFindChance",           effectByRarity: [null, null, -0.10, -0.15, -0.20] },
    ],
  },
  {
    id: "ore_injector",
    type: "item",
    name: "Рудный инжектор",
    icon: "⚗️",
    desc: "Удар по бреши восстанавливает +15 топлива. −5% скорость бура.",
    category: "поиск_бреши",
    tags: ["поиск_бреши"],
    minRarity: 2,
    baseCost: 45,
    effect: [
      { stat: "weakSpotFuelGain", effectByRarity: [null, null, 15, 25, 40] },
      { stat: "strikeSpeed",      effectByRarity: [null, null, -5, -5, -5] },
    ],
  },
  {
    id: "sharp_tip",
    type: "item",
    name: "Заточенный наконечник",
    icon: "🗡️",
    desc: "+5% шанс бреши. +0.3 урон по бреши.",
    category: "поиск_бреши",
    tags: ["поиск_бреши"],
    minRarity: 1,
    baseCost: 35,
    effect: [
      { stat: "weakSpotChance", effectByRarity: [null, 0.05, 0.08, 0.12, 0.18] },
      { stat: "weakSpotMult",   effectByRarity: [null, 0.3,  0.5,  0.8,  1.2 ] },
    ],
  },
  {
    id: "sniper_scope",
    type: "item",
    name: "Снайперский прицел",
    icon: "🎯",
    desc: "+4% шанс бреши. +0.5 урон по бреши. Пробитие.",
    category: "поиск_бреши",
    tags: ["поиск_бреши"],
    minRarity: 2,
    baseCost: 50,
    unique: true,
    effect: [
      { stat: "weakSpotChance",  effectByRarity: [null, null, 0.04, 0.07, 0.12] },
      { stat: "weakSpotMult",    effectByRarity: [null, null, 0.5,  0.8,  1.2 ] },
      { stat: "weakSpotPierce",  effectByRarity: [null, null, 1,    1,    1   ] },
    ],
  },
  {
    id: "loop_booster",
    type: "item",
    name: "Ускоритель замыкания",
    icon: "⚡",
    desc: "+5% скорость автозамыкания.",
    category: "контур",
    tags: ["контур"],
    minRarity: 1,
    baseCost: 30,
    effect: { stat: "speedOfAutoClose", effectByRarity: [null, 5, 8, 12, 18] },
  },
  {
    id: "contour_charge",
    type: "item",
    name: "Контурный заряд",
    icon: "🔋",
    desc: "+1 уровень контурного заряда. +10% длительность эффектов.",
    category: "контур",
    tags: ["контур"],
    minRarity: 2,
    baseCost: 50,
    effect: [
      { stat: "loopChargeLevel",  effectByRarity: [null, null, 1, 1, 2] },
      { stat: "effectDurationRate", effectByRarity: [null, null, 0.10, 0.18, 0.28] },
    ],
  },
  {
    id: "black_market",
    type: "item",
    name: "Чёрный рынок",
    icon: "🏴",
    desc: "−10% к стоимости предметов в магазине.",
    category: "economy",
    tags: ["economy"],
    minRarity: 1,
    baseCost: 45,
    effect: {
      stat: "shopPriceDiscount",
      effectByRarity: [null, 0.10, 0.15, 0.20, 0.30],
    },
  },
];

export const ALL_GOODS = [...ALL_EQUIPMENT, ...ALL_ITEMS];
