// Planned items — not yet implemented in game.
// Fields: id, name, icon, category, stats (affected), concept, difficulty ('easy'|'medium'|'hard')

export const TODO_ITEMS = [

  // ── Heat ────────────────────────────────────────────────────────────────────
  {
    id: 'heat_accumulator',
    name: 'Термоаккумулятор',
    icon: '🌡️',
    category: 'heat',
    stats: ['maxHeat'],
    concept: '+maxHeat. Можно дольше оставаться в горячей зоне до перегрева.',
    difficulty: 'easy',
  },
  {
    id: 'cooling_circuit',
    name: 'Охлаждающий контур',
    icon: '❄️',
    category: 'heat',
    stats: ['heatRate'],
    concept: 'Снижает скорость набора тепла (heatRate). Trade-off: меньше урона от жара.',
    difficulty: 'easy',
  },
  {
    id: 'heat_pump',
    name: 'Жаровой насос',
    icon: '🔆',
    category: 'heat',
    stats: ['heatDamageBonus'],
    concept: '+heatDamageBonus. Урон от ударов масштабируется с текущим уровнем heat.',
    difficulty: 'medium',
  },
  {
    id: 'explosive_condenser',
    name: 'Взрывной конденсор',
    icon: '💥',
    category: 'heat',
    stats: ['heatExplosionDamageBonus', 'heatExplosionRadiusBonus'],
    concept: 'При перегреве взрыв наносит больше урона и имеет больший радиус.',
    difficulty: 'easy',
  },
  {
    id: 'heat_shield',
    name: 'Тепловой щит',
    icon: '🛡️',
    category: 'heat',
    stats: ['armor', 'heat'],
    concept: 'Броня пропорциональна текущему уровню heat. Горячий — защищённый.',
    difficulty: 'hard',
  },

  // ── Fuel ────────────────────────────────────────────────────────────────────
  {
    id: 'expanded_tank',
    name: 'Расширенный бак',
    icon: '⛽',
    category: 'maintenance',
    stats: ['maxFuel'],
    concept: '+maxFuel. Дольше бурим без возврата на базу.',
    difficulty: 'easy',
  },
  {
    id: 'fuel_economizer',
    name: 'Экономайзер',
    icon: '💧',
    category: 'maintenance',
    stats: ['fuelDrainRate'],
    concept: 'Снижает fuelDrainRate — топливо расходуется медленнее.',
    difficulty: 'easy',
  },
  {
    id: 'ore_injector',
    name: 'Рудный инжектор',
    icon: '⚗️',
    category: 'maintenance',
    stats: ['fuelDrainRate', 'strikeSpeed'],
    concept: 'При каждом ударе по жиле восстанавливает немного топлива. −5% strikeSpeed.',
    difficulty: 'hard',
  },
  {
    id: 'boosted_feed',
    name: 'Форсированная подача',
    icon: '🚀',
    category: 'maintenance',
    stats: ['strikeSpeed', 'fuelDrainRate'],
    concept: '+20% strikeSpeed, но +30% fuelDrainRate. Быстро, расточительно.',
    difficulty: 'easy',
  },

  // ── Vision / radar ──────────────────────────────────────────────────────────
  {
    id: 'scanner_lens',
    name: 'Линза сканера',
    icon: '🔭',
    category: 'basic',
    stats: ['visionRadius'],
    concept: '+visionRadius. Видим дальше, лучше планируем маршрут.',
    difficulty: 'easy',
  },
  {
    id: 'deep_radar',
    name: 'Глубинный радар',
    icon: '📡',
    category: 'basic',
    stats: ['visionRadius'],
    concept: 'Маяки и крупные жилы видны через туман войны на расстоянии N клеток.',
    difficulty: 'medium',
  },
  {
    id: 'echo_sounder',
    name: 'Эхолот',
    icon: '〰️',
    category: 'basic',
    stats: ['visionRadius'],
    concept: 'Разово подсвечивает ближайшую необнаруженную богатую жилу при покупке.',
    difficulty: 'hard',
  },

  // ── Economy ─────────────────────────────────────────────────────────────────
  {
    id: 'gold_fever',
    name: 'Золотая лихорадка',
    icon: '🤑',
    category: 'economy',
    stats: ['goldBonus'],
    concept: '+goldBonus%. Все доходы с жил умножаются.',
    difficulty: 'easy',
  },
  {
    id: 'insider',
    name: 'Инсайдер',
    icon: '🎲',
    category: 'economy',
    stats: ['luck'],
    concept: '+luck. Шанс лучших предметов в магазине и ценных жил на карте.',
    difficulty: 'easy',
  },
  {
    id: 'black_market',
    name: 'Чёрный рынок',
    icon: '🏴',
    category: 'economy',
    stats: ['itemPrice'],
    concept: 'Снижает стоимость предметов в магазине на N%.',
    difficulty: 'medium',
  },
  {
    id: 'insurance',
    name: 'Страховка',
    icon: '📋',
    category: 'economy',
    stats: ['goldBonus'],
    concept: 'При потере HP сохраняет часть небезопасного золота (не теряем всё).',
    difficulty: 'hard',
  },

  // ── Combat / crit ────────────────────────────────────────────────────────────
  {
    id: 'sharp_tip',
    name: 'Заточенный наконечник',
    icon: '🗡️',
    category: 'basic',
    stats: ['critChance'],
    concept: '+critChance. Увеличивает шанс критического удара по породе.',
    difficulty: 'easy',
  },
  {
    id: 'sniper_scope',
    name: 'Снайперский прицел',
    icon: '🎯',
    category: 'basic',
    stats: ['critMultiplier'],
    concept: '+critMultiplier. Критические удары дробят больше блоков за раз.',
    difficulty: 'easy',
  },
  {
    id: 'rock_armor',
    name: 'Броня из породы',
    icon: '🪨',
    category: 'basic',
    stats: ['armor'],
    concept: '+armor. Снижает урон от опасных зон. Масштабируется с глубиной.',
    difficulty: 'medium',
  },
  {
    id: 'ricochet_tip',
    name: 'Рикошет',
    icon: '↩️',
    category: 'basic',
    stats: ['critChance'],
    concept: 'Удар рикошетит на соседний блок при крите. Шанс попасть по двум блокам.',
    difficulty: 'hard',
  },

  // ── Loop / contour ───────────────────────────────────────────────────────────
  {
    id: 'loop_booster',
    name: 'Ускоритель замыкания',
    icon: '⚡',
    category: 'economy',
    stats: ['speedOfAutoClose'],
    concept: '+speedOfAutoClose. Автозамыкание контура происходит быстрее.',
    difficulty: 'easy',
  },
  {
    id: 'contour_charge',
    name: 'Контурный заряд',
    icon: '🔋',
    category: 'economy',
    stats: ['loopChargeLevel'],
    concept: '+loopChargeLevel. Замкнутые контуры дают бонусный заряд к следующему.',
    difficulty: 'medium',
  },
  {
    id: 'perfectionist',
    name: 'Перфекционист',
    icon: '🏅',
    category: 'economy',
    stats: ['goldBonus'],
    concept: 'Если контур замкнут быстро (< N сек) — бонус +50% к золоту за него.',
    difficulty: 'hard',
  },
  {
    id: 'beacon_amp',
    name: 'Маяковый усилитель',
    icon: '📶',
    category: 'economy',
    stats: ['goldBonus'],
    concept: 'Контуры рядом с активированным маяком дают +N золота сверху.',
    difficulty: 'medium',
  },

  // ── Misc / survivability ─────────────────────────────────────────────────────
  {
    id: 'second_chance',
    name: 'Второй шанс',
    icon: '💫',
    category: 'basic',
    stats: ['maxHp'],
    concept: 'Один раз за погружение выживает с 1 HP вместо гибели. Не складывается.',
    difficulty: 'hard',
  },
  {
    id: 'adrenaline',
    name: 'Адреналин',
    icon: '💉',
    category: 'basic',
    stats: ['strikeSpeed'],
    concept: '+30% strikeSpeed при HP ≤ 1. Отчаяние ускоряет бур.',
    difficulty: 'medium',
  },
  {
    id: 'heat_converter',
    name: 'Переработчик жара',
    icon: '♻️',
    category: 'heat',
    stats: ['goldBonus', 'heatRate'],
    concept: 'Конвертирует избыточный heat в золото при замыкании контура.',
    difficulty: 'hard',
  },
  {
    id: 'first_strike',
    name: 'Инициатор',
    icon: '⚔️',
    category: 'basic',
    stats: ['damageBonus'],
    concept: 'Первый удар в новом погружении (после базы) наносит двойной урон.',
    difficulty: 'medium',
  },

];
