// Planned items — not yet implemented in game.
// Fields: id, name, icon, category, statWeights (affected stats with direction), concept, difficulty ('easy'|'medium'|'hard')

export const TODO_ITEMS = [

  // ── Heat ────────────────────────────────────────────────────────────────────
  {
    id: 'heat_accumulator',
    name: 'Термоаккумулятор',
    icon: '🌡️',
    category: 'heat',
    statWeights: { maxHeat: 1 },
    concept: '+maxHeat. Можно дольше оставаться в горячей зоне до перегрева.',
    difficulty: 'easy',
  },
  {
    id: 'cooling_circuit',
    name: 'Охлаждающий контур',
    icon: '❄️',
    category: 'heat',
    statWeights: { heatRate: -1, concentration: -2 },
    concept: 'Снижает скорость набора тепла (heatRate).',
    difficulty: 'easy',
  },
  {
    id: 'explosive_condenser',
    name: 'Взрывной конденсор',
    icon: '💥',
    category: 'heat',
    statWeights: { heatExplosionDamageBonus: 1, heatExplosionRadiusBonus: 1, concentration: -1 },
    concept: 'При перегреве взрыв наносит больше урона и имеет больший радиус.',
    difficulty: 'easy',
  },

  // ── Выживание ────────────────────────────────────────────────────────────────
  {
    id: 'expanded_tank',
    name: 'Расширенный бак',
    icon: '⛽',
    category: 'выживание',
    statWeights: { maxFuel: 1, fuelDrainRate: 1 },
    concept: '+maxFuel. Дольше бурим без возврата на базу.',
    difficulty: 'easy',
  },
  {
    id: 'insurance',
    name: 'Страховка',
    icon: '📋',
    category: 'выживание',
    statWeights: { goldBonus: 1 },
    concept: 'При потере HP сохраняет часть небезопасного золота (не теряем всё). (нужна новая стата)',
    difficulty: 'hard',
  },
  {
    id: 'adrenaline',
    name: 'Адреналин',
    icon: '💉',
    category: 'выживание',
    statWeights: { strikeSpeed: 1 },
    concept: '+30% strikeSpeed при HP ≤ 1. Отчаяние ускоряет бур.',
    difficulty: 'medium',
  },
  {
    id: 'fuel_converter',
    name: 'Переработчик топлива',
    icon: '♻️',
    category: 'выживание',
    statWeights: { goldBonus: 1, heatRate: 1, maxFuel: -1 },
    concept: 'При избыточном топливе начинается форсаж.',
    difficulty: 'hard',
  },

  // ── Maintenance ──────────────────────────────────────────────────────────────
  {
    id: 'boosted_feed',
    name: 'Форсированная подача',
    icon: '🚀',
    category: 'maintenance',
    statWeights: { strikeSpeed: 2, fuelDrainRate: 1 },
    concept: 'Быстро, расточительно.',
    difficulty: 'easy',
  },
  {
    id: 'first_strike',
    name: 'Инициатор',
    icon: '⚔️',
    category: 'maintenance',
    statWeights: { damageBonus: 1 },
    concept: 'Первые секунды после активации маяка будут с форсажем.',
    difficulty: 'medium',
  },

  // ── Economy ─────────────────────────────────────────────────────────────────
  {
    id: 'fuel_economizer',
    name: 'Экономайзер',
    icon: '💧',
    category: 'economy',
    statWeights: { fuelDrainRate: -2, drillPower: -1 },
    concept: 'Снижает fuelDrainRate — топливо расходуется медленнее.',
    difficulty: 'easy',
  },
  {
    id: 'gold_fever',
    name: 'Золотая лихорадка',
    icon: '🤑',
    category: 'economy',
    statWeights: { goldBonus: 1 },
    concept: '+goldBonus%. Все доходы с жил умножаются.',
    difficulty: 'easy',
  },
  {
    id: 'insider',
    name: 'Инсайдер',
    icon: '🎲',
    category: 'economy',
    statWeights: { luck: 2, xpBonusMultiplier: -1 },
    concept: '+luck. Шанс лучших предметов в магазине и ценных жил на карте.',
    difficulty: 'easy',
  },
  {
    id: 'black_market',
    name: 'Чёрный рынок',
    icon: '🏴',
    category: 'economy',
    statWeights: { itemPrice: 1 },
    concept: 'Снижает стоимость предметов в магазине на N%.',
    difficulty: 'medium',
  },
  {
    id: 'perfectionist',
    name: 'Перфекционист',
    icon: '🏅',
    category: 'economy',
    statWeights: { goldBonus: 1, bonusFindChance: -1 },
    concept: 'Золотые жилы добытые взрывом контура дают больше золота. (нужна новая стата)',
    difficulty: 'hard',
  },

  // ── Basic ────────────────────────────────────────────────────────────────────
  {
    id: 'scanner_lens',
    name: 'Линза сканера',
    icon: '🔭',
    category: 'basic',
    statWeights: { visionRadius: 1 },
    concept: '+visionRadius. Видим дальше, лучше планируем маршрут.',
    difficulty: 'easy',
  },

  // ── Поиск бреши ─────────────────────────────────────────────────────────────
  {
    id: 'ore_injector',
    name: 'Рудный инжектор',
    icon: '⚗️',
    category: 'поиск_бреши',
    statWeights: { strikeSpeed: 1, weakSpotChance: 1, damageBonus: -1 },
    concept: 'При ударе по бреши восстанавливается немного топлива.',
    difficulty: 'hard',
  },
  {
    id: 'sharp_tip',
    name: 'Заточенный наконечник',
    icon: '🗡️',
    category: 'поиск_бреши',
    statWeights: { weakSpotChance: 2, weakSpotMult: 1 },
    concept: '',
    difficulty: 'easy',
  },
  {
    id: 'sniper_scope',
    name: 'Снайперский прицел',
    icon: '🎯',
    category: 'поиск_бреши',
    statWeights: { weakSpotChance: 1, weakSpotMult: 2 },
    concept: 'При попадании по бреши наносится такой же урон следующему тайлу (пробитие). Уникальный.',
    difficulty: 'easy',
  },

  // ── Контур ──────────────────────────────────────────────────────────────────
  {
    id: 'loop_capacitor',
    name: 'Конденсатор контура',
    icon: '🔌',
    category: 'контур',
    statWeights: { loopChargeLevel: 2, speedOfAutoClose: -1 },
    concept: 'Накапливает энергию между контурами — каждый заряженный контур мощнее, но автозамыкание медленнее.',
    difficulty: 'medium',
  },
  {
    id: 'chain_reaction',
    name: 'Цепная реакция',
    icon: '⛓️',
    category: 'контур',
    statWeights: { loopPerkLevel: 2, effectDurationRate: 1, idleAutoCloseDelay: 1 },
    concept: 'Каждый последующий контур усиливает следующий. Дольше ждёшь начала автозамыкания.',
    difficulty: 'hard',
  },
  {
    id: 'idle_optimizer',
    name: 'Оптимизатор простоя',
    icon: '⏱️',
    category: 'контур',
    statWeights: { idleAutoCloseDelay: -2, loopChargeLevel: -1 },
    concept: 'Сокращает задержку перед автозамыканием. Контуры слабее, но срабатывают быстрее.',
    difficulty: 'easy',
  },
  {
    id: 'loop_booster',
    name: 'Ускоритель замыкания',
    icon: '⚡',
    category: 'контур',
    statWeights: { speedOfAutoClose: 2 },
    concept: '+speedOfAutoClose. Автозамыкание контура происходит быстрее.',
    difficulty: 'easy',
  },
  {
    id: 'contour_charge',
    name: 'Контурный заряд',
    icon: '🔋',
    category: 'контур',
    statWeights: { loopChargeLevel: 1, effectDurationRate: 1 },
    concept: 'Замкнутый контур начинает форсаж (если успешно сломал больше четырёх блоков) на 4 сек.',
    difficulty: 'medium',
  },


  // ── Heat ── (дополнительные) ─────────────────────────────────────────────────
  {
    id: 'heat_engine',
    name: 'Тепловой двигатель',
    icon: '🔆',
    category: 'heat',
    statWeights: { strikeSpeed: 2, heatRate: 2, maxHeat: -1 },
    concept: 'Конвертирует нагрев в скорость бура. Чем горячее — тем быстрее. Но перегрев ближе.',
    difficulty: 'medium',
  },
  {
    id: 'pressure_valve',
    name: 'Предохранительный клапан',
    icon: '🎚️',
    category: 'heat',
    statWeights: { heatRate: -2, heatDamageBonus: -1, maxHeat: -1 },
    concept: 'Сбрасывает heat автоматически при приближении к пределу. Снижает потолок и урон от нагрева.',
    difficulty: 'easy',
  },

  // ── Maintenance ── (дополнительные) ─────────────────────────────────────────
  {
    id: 'fuel_injector',
    name: 'Топливный инжектор',
    icon: '⚙️',
    category: 'maintenance',
    statWeights: { drillPower: 2, fuelDrainRate: 2 },
    concept: 'Впрыскивает топливо в удар — больше урона, но расход растёт пропорционально.',
    difficulty: 'medium',
  },
  {
    id: 'wear_sensor',
    name: 'Датчик износа',
    icon: '📟',
    category: 'maintenance',
    statWeights: { fuelDrainRate: -2, strikeSpeed: -1 },
    concept: 'Снижает расход топлива за счёт более аккуратной работы бура. Скорость страдает.',
    difficulty: 'easy',
  },

  // ── Выживание ── (дополнительные) ───────────────────────────────────────────
  {
    id: 'emergency_kit',
    name: 'Аварийный комплект',
    icon: '🩹',
    category: 'выживание',
    statWeights: { healPerLevel: 2, maxHp: -1 },
    concept: 'Восстанавливает больше здоровья с каждым уровнем, но максимальный запас HP ниже.',
    difficulty: 'medium',
  },
  {
    id: 'reinforced_frame',
    name: 'Усиленная рама',
    icon: '🦺',
    category: 'выживание',
    statWeights: { armor: 2, strikeSpeed: -1 },
    concept: 'Тяжёлая броня гасит урон, но замедляет цикл удара.',
    difficulty: 'easy',
  },

  // ── Поиск бреши ── (дополнительные) ─────────────────────────────────────────
  {
    id: 'resonance_tip',
    name: 'Резонансный наконечник',
    icon: '〰️',
    category: 'поиск_бреши',
    statWeights: { weakSpotChance: 2, drillPower: -1 },
    concept: 'Каждый удар немного расшатывает породу. Шанс бреши выше, но базовый урон ниже.',
    difficulty: 'easy',
  },
  {
    id: 'fracture_lens',
    name: 'Линза трещин',
    icon: '🔬',
    category: 'поиск_бреши',
    statWeights: { weakSpotMult: 2, visionRadius: 1, luck: -1 },
    concept: 'Подсвечивает скрытые трещины в породе. Урон по бреши выше, но удача хуже.',
    difficulty: 'medium',
  },

  // ── Навигация ────────────────────────────────────────────────────────────────
  {
    id: 'crystal_detector',
    name: 'Детектор кристаллов',
    icon: '💎',
    category: 'навигация',
    statWeights: { radarCrystalModule: 1, visionRadius: 1, luck: -1 },
    concept: 'Включает кольцевые подсказки на ближайшие кристаллы. Чутьё на лут снижается.',
    difficulty: 'easy',
  },
  {
    id: 'deep_scanner',
    name: 'Глубинный сканер',
    icon: '📡',
    category: 'навигация',
    statWeights: { visionRadius: 2, strikeSpeed: -1 },
    concept: 'Существенно расширяет радиус обзора, но массив антенн нагружает механику бура.',
    difficulty: 'easy',
  },

  // ── Экономика ── (дополнительные) ───────────────────────────────────────────
  {
    id: 'tax_evasion',
    name: 'Уклонение от налогов',
    icon: '🧾',
    category: 'economy',
    statWeights: { xpBonusMultiplier: 2, miningGoldBonusMultiplier: -1 },
    concept: 'Перекладывает прибыль в опыт. Золота меньше, уровни быстрее.',
    difficulty: 'medium',
  },
  {
    id: 'risk_premium',
    name: 'Рисковая надбавка',
    icon: '🎰',
    category: 'economy',
    statWeights: { bonusFindChance: 2, armor: -1 },
    concept: 'Больше шансов на случайную находку — но меньше защиты.',
    difficulty: 'medium',
  },

  // ── Алхимия ──────────────────────────────────────────────────────────────────
  {
    id: 'beacon_catalyst',
    name: 'Маяковый катализатор',
    icon: '🗼',
    category: 'алхимия',
    statWeights: { bonusFindChance: -1, effectDurationRate: 1 },
    concept: 'Активация маяка мгновенно завершает текущий рецепт. Уникальный.',
    difficulty: 'hard',
  },
  {
    id: 'recipe_reroller',
    name: 'Реролл рецепта',
    icon: '🎲',
    category: 'алхимия',
    statWeights: { luck: 1, xpBonusMultiplier: -1 },
    concept: 'Добавляет N реролов к награде за выполненный рецепт.',
    difficulty: 'medium',
  },
  {
    id: 'crystal_gold',
    name: 'Золотой кристалл',
    icon: '💎',
    category: 'алхимия',
    statWeights: { miningGoldBonusMultiplier: 2, xpBonusMultiplier: -1 },
    concept: 'Подбор кристалла даёт золото вместо части опыта.',
    difficulty: 'medium',
  },
  {
    id: 'xp_amplifier',
    name: 'Усилитель опыта',
    icon: '🔮',
    category: 'алхимия',
    statWeights: { xpBonusMultiplier: 2, miningGoldBonusMultiplier: -1 },
    concept: 'Увеличивает весь получаемый опыт. Золото с жил чуть ниже.',
    difficulty: 'easy',
  },
  {
    id: 'crystal_xp',
    name: 'Кристальный опыт',
    icon: '✨',
    category: 'алхимия',
    statWeights: { xpBonusMultiplier: 2, luck: -1 },
    concept: 'Подбор кристалла даёт дополнительный опыт.',
    difficulty: 'easy',
  },
  {
    id: 'level_catalyst',
    name: 'Катализатор уровня',
    icon: '⬆️',
    category: 'алхимия',
    statWeights: { xpBonusMultiplier: -1, bonusFindChance: 1 },
    concept: 'Получение уровня мгновенно завершает текущий рецепт. Уникальный.',
    difficulty: 'hard',
  },

  // ── Оглушение ────────────────────────────────────────────────────────────────
  {
    id: 'stun_detonator',
    name: 'Детонатор оглушения',
    icon: '💢',
    category: 'выживание',
    statWeights: { concentration: 1, explosionDamageMultiplier: 2, armor: -1 },
    concept: 'При оглушении немедленно срабатывает взрыв вокруг бура. Броня ниже — больше риска.',
    difficulty: 'hard',
  },
  {
    id: 'stun_reservoir',
    name: 'Резервуар оглушения',
    icon: '🫙',
    category: 'выживание',
    statWeights: { concentration: 1, fuelPickupBonus: 2, maxFuel: -1 },
    concept: 'При оглушении выбрасывает порцию топлива. Макс. бак меньше — зато стан превращается в дозаправку.',
    difficulty: 'medium',
  },
  {
    id: 'stun_afterburner',
    name: 'Форсаж после стана',
    icon: '⚡',
    category: 'выживание',
    statWeights: { concentration: 1, strikeSpeed: 2, effectDurationRate: 1 },
    concept: 'После оглушения бур уходит в форсаж на несколько секунд. Чем дольше стан — тем длиннее разгон.',
    difficulty: 'medium',
  },

  // ── Ракеты ───────────────────────────────────────────────────────────────────
  {
    id: 'breach_missile',
    name: 'Бреш-ракета',
    icon: '🎯',
    category: 'ракеты',
    statWeights: { weakSpotChance: 1, weakSpotMult: -1, explosionDamageMultiplier: 2 },
    concept: 'При попадании в брешь автоматически запускает ракету. Бреши сложнее пробить самому.',
    difficulty: 'medium',
  },
  {
    id: 'cryo_rocket',
    name: 'Крио-ракета',
    icon: '❄️',
    category: 'ракеты',
    statWeights: { heatRate: -2, explosionDamageMultiplier: 1, maxHeat: -1 },
    concept: 'При остывании на N единиц запускает ракету. Чем активнее охлаждение — тем чаще выстрелы.',
    difficulty: 'hard',
  },
  {
    id: 'fuel_rocket',
    name: 'Топливная ракета',
    icon: '⛽',
    category: 'ракеты',
    statWeights: { fuelPickupBonus: -1, explosionDamageMultiplier: 2, fuelDrainRate: 1 },
    concept: 'При пополнении топлива запускает ракету. Часть топлива уходит на выстрел.',
    difficulty: 'hard',
  },
  {
    id: 'rocket_booster',
    name: 'Ракетный ускоритель',
    icon: '🚀',
    category: 'ракеты',
    statWeights: { explosionDamageMultiplier: 2, heatRate: 1 },
    concept: 'Усиливает взрывы, но каждый выстрел добавляет нагрев.',
    difficulty: 'medium',
  },
  {
    id: 'cluster_warhead',
    name: 'Кассетная боеголовка',
    icon: '💣',
    category: 'ракеты',
    statWeights: { heatExplosionRadiusBonus: 2, explosionDamageMultiplier: 1, damageBonus: -1 },
    concept: 'Взрыв разлетается на несколько осколков. Площадь больше, точечный урон ниже.',
    difficulty: 'medium',
  },
  {
    id: 'shaped_charge',
    name: 'Кумулятивный заряд',
    icon: '🎯',
    category: 'ракеты',
    statWeights: { damageBonus: 2, heatExplosionRadiusBonus: -1, fuelDrainRate: 1 },
    concept: 'Концентрирует взрыв в точку. Урон максимальный, радиус минимальный.',
    difficulty: 'medium',
  },

];
