/**
 * Конфигурация магазина прокачки.
 *
 * Структура:
 *   SHOP_TREES — массив деревьев прокачки.
 *
 * Каждое дерево:
 *   id       — уникальный строковый идентификатор
 *   name     — отображаемое название
 *   icon     — символ/emoji для таба
 *   nodes    — массив узлов дерева
 *
 * Каждый узел:
 *   id       — уникальный строковый идентификатор
 *   name     — отображаемое название
 *   icon     — символ/emoji
 *   desc     — описание эффекта одного уровня
 *   maxLevel — максимальный уровень (1 = разовая покупка)
 *   costs    — массив цен в золотое по уровням (length == maxLevel)
 *   row      — строка в сетке дерева (0 = верхний ряд)
 *   col      — столбец в сетке дерева (0 = левый)
 *   requires — id узла-родителя (null = корневой узел)
 *
 * Чтобы следующий уровень стал доступен, предыдущий должен быть куплен хотя бы на 1.
 * Чтобы дочерний узел (requires) стал доступен, родитель должен быть хотя бы на уровне 1.
 */

export const SHOP_TREES = [
  {
    id: "drilling",
    name: "Бурение",
    icon: "⛏",
    nodes: [
      {
        id: "drill_power",
        name: "Мощность бура",
        icon: "D",
        desc: "+0.5 к силе удара за уровень",
        maxLevel: 3,
        costs: [40, 80, 150],
        row: 0,
        col: 1,
        requires: null,
      },
      {
        id: "side_drills",
        name: "Боковые буры",
        icon: "⫼",
        desc: "Каждый удар бьёт боковые клетки",
        maxLevel: 2,
        costs: [60, 130],
        row: 1,
        col: 0,
        requires: "drill_power",
      },
      {
        id: "long_drill",
        name: "Длинный бур",
        icon: "⇢",
        desc: "+20% урон по следующему тайлу вперёд",
        maxLevel: 3,
        costs: [60, 110, 180],
        row: 1,
        col: 1,
        requires: "drill_power",
      },
      {
        id: "diagonal_drills",
        name: "Диагональные буры",
        icon: "✣",
        desc: "+20% урон по двум диагоналям вперёд",
        maxLevel: 3,
        costs: [60, 110, 180],
        row: 1,
        col: 2,
        requires: "drill_power",
      },
      {
        id: "spike_boost",
        name: "Шиповой форсаж",
        icon: "✹",
        desc: "Разбитые шипы дают overdrive-баф на 6/9/12 секунд",
        maxLevel: 3,
        costs: [70, 130, 200],
        row: 2,
        col: 0,
        requires: "side_drills",
      },
      {
        id: "speed",
        name: "Скорость бура",
        icon: "S",
        desc: "Увеличивает скорость бурения",
        maxLevel: 3,
        costs: [40, 90, 160],
        row: 3,
        col: 0,
        requires: null,
      },
    ],
  },

  {
    id: "fuel",
    name: "Топливо",
    icon: "⛽",
    nodes: [
      {
        id: "fuel_tank",
        name: "Расширенный бак",
        icon: "◌",
        desc: "+60 к максимуму топлива",
        maxLevel: 3,
        costs: [35, 70, 120],
        row: 0,
        col: 1,
        requires: null,
      },
      {
        id: "fuel_circuit",
        name: "Топливный контур",
        icon: "⛽",
        desc: "Каждый тайловый перк даёт +50 топлива",
        maxLevel: 1,
        costs: [80],
        row: 1,
        col: 0,
        requires: "fuel_tank",
      },
      {
        id: "recirculator",
        name: "Рециркулятор",
        icon: "●",
        desc: "+2 золота и +2 топлива за каждый разрушенный блок",
        maxLevel: 2,
        costs: [80, 150],
        row: 1,
        col: 1,
        requires: "fuel_tank",
      },
      {
        id: "low_fuel_boost",
        name: "Форсаж на нуле",
        icon: "⏚",
        desc: "Чем меньше топлива, тем быстрее следующий удар",
        maxLevel: 3,
        costs: [70, 130, 200],
        row: 1,
        col: 2,
        requires: "fuel_tank",
      },
      {
        id: "overload",
        name: "Перегрузка",
        icon: "⚡",
        desc: "Переполнение топлива даёт форсаж, затем взрыв и оглушение",
        maxLevel: 1,
        costs: [120],
        row: 2,
        col: 1,
        requires: "recirculator",
      },
      {
        id: "tank_boost",
        name: "Усиленный бак",
        icon: "◌",
        desc: "Бак даёт больше топлива, но растёт расход в секунду",
        maxLevel: 3,
        costs: [60, 120, 200],
        row: 2,
        col: 2,
        requires: "low_fuel_boost",
      },
      {
        id: "contour_recovery",
        name: "Рекуперация контура",
        icon: "↺",
        desc: "Возврат по своему контуру даёт топливо за шаг",
        maxLevel: 3,
        costs: [70, 130, 200],
        row: 2,
        col: 1,
        requires: "fuel_circuit",
      },
    ],
  },

  {
    id: "vision",
    name: "Обзор",
    icon: "◉",
    nodes: [
      {
        id: "geo_lens",
        name: "Гео-линза",
        icon: "◉",
        desc: "+2 к радиусу обзора",
        maxLevel: 2,
        costs: [60, 130],
        row: 0,
        col: 0,
        requires: null,
      },
      {
        id: "radar_module",
        name: "Радарный модуль",
        icon: "⌖",
        desc: "Радар показывает ближайшие кристаллы",
        maxLevel: 1,
        costs: [80],
        row: 0,
        col: 1,
        requires: null,
      },
      {
        id: "radar_booster",
        name: "Усилитель радара",
        icon: "R",
        desc: "+2 заряда радара при каждом получении",
        maxLevel: 3,
        costs: [50, 100, 160],
        row: 1,
        col: 0,
        requires: "geo_lens",
      },
      {
        id: "cooling_pulse",
        name: "Импульс остывания",
        icon: "⌁",
        desc: "При полном остывании даёт 5 сек радара",
        maxLevel: 3,
        costs: [90, 160, 240],
        row: 2,
        col: 0,
        requires: null,
      },
    ],
  },

  {
    id: "contour",
    name: "Контур",
    icon: "◎",
    nodes: [
      {
        id: "contour_charge",
        name: "Контурный заряд",
        icon: "⬡",
        desc: "После замыкания контура — временный бонус к урону бура",
        maxLevel: 4,
        costs: [70, 130, 200, 290],
        row: 0,
        col: 1,
        requires: null,
      },
      {
        id: "contour_trophy",
        name: "Контурный трофей",
        icon: "◈",
        desc: "Большой контур может создать случайный перк внутри",
        maxLevel: 2,
        costs: [90, 170],
        row: 1,
        col: 0,
        requires: "contour_charge",
      },
      {
        id: "auto_contour",
        name: "Автоконтур",
        icon: "◎",
        desc: "-1 сек к задержке автозамыкания контура",
        maxLevel: 3,
        costs: [80, 150, 230],
        row: 1,
        col: 1,
        requires: "contour_charge",
      },
      {
        id: "contour_resonance",
        name: "Контурный резонанс",
        icon: "⟲",
        desc: "+1% урона за каждую единицу длины контура",
        maxLevel: 4,
        costs: [80, 150, 230, 330],
        row: 1,
        col: 2,
        requires: "contour_charge",
      },
    ],
  },

  {
    id: "heat",
    name: "Нагрев",
    icon: "☇",
    nodes: [
      {
        id: "heat_sink",
        name: "Теплоотвод",
        icon: "⬢",
        desc: "+20 к пределу нагрева до перегрева",
        maxLevel: 3,
        costs: [60, 110, 170],
        row: 0,
        col: 1,
        requires: null,
      },
      {
        id: "heat_drill",
        name: "Накал бура",
        icon: "❉",
        desc: "+20% урона бура в зависимости от нагрева",
        maxLevel: 3,
        costs: [70, 130, 200],
        row: 1,
        col: 0,
        requires: "heat_sink",
      },
      {
        id: "thermo_charge",
        name: "Термозаряд",
        icon: "☇",
        desc: "+1 к урону и +0.5 к радиусу взрыва от перегрева",
        maxLevel: 3,
        costs: [70, 130, 200],
        row: 1,
        col: 1,
        requires: "heat_sink",
      },
      {
        id: "accel_dampers",
        name: "Разгонные демпферы",
        icon: "◍",
        desc: "Сокращают оглушение и ускоряют набор нагрева",
        maxLevel: 3,
        costs: [80, 150, 230],
        row: 1,
        col: 2,
        requires: "heat_sink",
      },
    ],
  },

  {
    id: "survival",
    name: "Выживание",
    icon: "✚",
    nodes: [
      {
        id: "reinforced_hull",
        name: "Усиленный корпус",
        icon: "✚",
        desc: "+1 к максимуму HP и лечит на 2",
        maxLevel: 3,
        costs: [60, 110, 180],
        row: 0,
        col: 0,
        requires: null,
      },
      {
        id: "ore_collector",
        name: "Ломосбор",
        icon: "●",
        desc: "+2 золота за каждый разрушенный блок",
        maxLevel: 3,
        costs: [50, 100, 170],
        row: 0,
        col: 2,
        requires: null,
      },
      {
        id: "adrenaline",
        name: "Перелив адреналина",
        icon: "❤",
        desc: "Overheal даёт 4 сек бафа, потом растёт до максимума 10",
        maxLevel: 3,
        costs: [90, 160, 240],
        row: 1,
        col: 0,
        requires: "reinforced_hull",
      },
      {
        id: "crystal_catalyst",
        name: "Кристальный катализатор",
        icon: "✧",
        desc: "Кристаллы начинают давать золото, потом fuel и HP",
        maxLevel: 3,
        costs: [100, 180, 270],
        row: 1,
        col: 2,
        requires: "ore_collector",
      },
    ],
  },

  {
    id: "missiles",
    name: "Ракеты",
    icon: "🚀",
    nodes: [
      {
        id: "sapper_charge",
        name: "Саперный заряд",
        icon: "✦",
        desc: "Каждые 15 блоков бросает ракету на дистанцию 3",
        maxLevel: 3,
        costs: [90, 160, 250],
        row: 2,
        col: 1,
        requires: null,
      },
      {
        id: "thermo_rockets",
        name: "Терморакеты",
        icon: "☄",
        desc: "Перегрев выпускает ракеты на дистанцию 1–3",
        maxLevel: 3,
        costs: [90, 160, 250],
        row: 2,
        col: 1,
        requires: "sapper_charge",
      },
      {
        id: "cryo_rockets",
        name: "Охлаждающие ракеты",
        icon: "❄",
        desc: "За каждые N остывшего нагрева выпускают ракету",
        maxLevel: 3,
        costs: [90, 160, 250],
        row: 2,
        col: 2,
        requires: "sapper_charge",
      },
    ],
  },

];
